name: Check for broken internal jump links

on:
  pull_request:
    branches:
      - production

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: npm install -g markdown-link-check
      - name: Check for broken internal jump links
        run: |
          markdown-link-check 'https://raw.githubusercontent.com/cloudflare/cloudflare-docs/production/content/**/*.md --config '{ "ignorePatterns": ["^https?://", "^mailto:", "^#", "^javascript:"] }'
